name: Java CI/CD with Gradle

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: memo-app
          path: build/libs/*.jar

      - name: Extract build version
        id: extract_version
        run: |
          version=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Extracted version $version"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body : ${{ steps.tag_version.outputs.changelog }}
          skipIfReleaseExists: true
          artifacts: build/libs/*.jar
          artifactContentType: application/java-archive
